language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.11.2
install: bundle install --jobs=3 --retry=3 --deployment --without development
addons:
    code_climate:
        repo_token: c5095ac9e2e622f87a86d61df49761b82cd6f91ea4b966372e40898dfe800956
before_script:
  - psql -eac 'create database travis_ci_test;' -U postgres
  - cp -v config/database.travis.yml config/database.yml
  - cp -v config/secrets.travis.yml config/secrets.yml
  - cp -v config/rabbitmq.travis.yml config/rabbitmq.yml
services:
  - postgresql
  - rabbitmq
script:  
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rspec spec/